server:
  port: 8088
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        namespace: 1e95f08b-9d9a-4b34-ae9d-8ad841f57264
        enabled: false

    sentinel:
      enabled: true
      transport:
        dashboard: 127.0.0.1:11080
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/my_cloud?useSSL=false&serverTimezone=UTC
    username: root
    password: suibianwanwan
  application:
    name: mycloud2-order
  rabbitmq:
    host: 121.4.54.141
    port: 5672
    username: admin
    password: 123456
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml

